### ISSUE TITLE
Adding widget script hides existing relations in CMS

### ISSUE THREAD

**Issue by dannykennedy** [d4rekanguok/netlify-cms-widgets#132]
Following the README, I added `<script src="https://unpkg.com/@ncwidgets/netlify-cms@^0.7.0/dist/netlify-cms.js"></script>`, instead of `<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>`.

However when I went to the CMS, the values I had previously populated in relation widgets were missing. (Although saving entries with `ncw-id` fields did not remove the relations in the `.md` files). The little tags in the CMS UI were simply not there any more. When I removed the ncw-id script and widget, and adding back the original script, the relation tags came back in the UI.

**Comment by d4rekanguok** [comment]
My apologies, since Netlify CMS has now included the relation features, I have not updated my build of Netlify CMS. 

Do you only use it for ncw-id + relation? Would this built in suggestion solve your case? https://github.com/netlify/netlify-cms/issues/3712#issuecomment-625132654

**Comment by dannykennedy** [comment]
Thanks @d4rekanguok , yes I found that comment after I added this issue and it works for me.
