### ISSUE TITLE
@ncwidgets/file-relation not working on self assignment

### ISSUE THREAD

**Issue by akubasa** [d4rekanguok/netlify-cms-widgets#17]
The widget is not working if you want to use it in the same list as it should get data from.

**Comment by d4rekanguok** [comment]
Hey @akubasa, thank you for reporting in -- the widget indeed doesn't work when it is in the same file with its target list. Worse yet, it crashes the browser :(

I'll have to take a deeper look to find a way to work around this or if it's possible at all. In the mean time, would you share your use case? Maybe there's a different kind of custom widgets that can help you.

**Comment by d4rekanguok** [comment]
The fix being discussed in #25 will close this, let's track this issue there!
