### ISSUE TITLE
hidden option for ncw-id widget

### ISSUE THREAD

**Issue by magomimmo** [d4rekanguok/netlify-cms-widgets#38]
When using the `ncw-id` widget to generate an unique id for a folder or file collection entry, generally speaking the CMS user is not interested in viewing that field in the UI. It could be useful to have an option to mark that field as `hidden: true` for such use case. I would also say that the default should be `true` as well.

**Comment by d4rekanguok** [comment]
Thanks Mimmo, this is much desirable. Back when I created this widget, widget with `hidden: true` are static: its value cannot be dynamically changed when editors create a new entry. Do you know if the new `hide` field can be used here?

**Comment by magomimmo** [comment]
The new option is named `hide: true` and is applicable to collection only, not to fields. It would be great to have, instead, a corresponding flag for the 'id_field` as well. Something like the following:

 ```yaml
     - label: 'Unique identifier'
       name: 'id'
       widget: 'ncw-id'
      hidden: true
```
Does it make sense to you?

**Comment by d4rekanguok** [comment]
Ah yes I understand now — I confused `hidden: true` with `widget: hidden`. From the widget side we can hide the UI control only, but we can't hide its label... perhaps there's a CSS hack we could use to completely hide everything.
